# Copyright 2015 Google Inc. All Rights Reserved.
application: hevs-android-tourism
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /clear_cache
  script: clear_cache.php
  login: admin

- url: /app_dev.php/.*
  script: web/app_dev.php

- url: /.*
  script: web/app.php

env_variables:
  CACHE_DIR: "gs://#default#/symfony/cache"
  LOG_DIR: "gs://#default#/symfony/log"

