# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.twig.locale_extension:
        public: false
        class: AppBundle\Twig\LocaleExtension
        arguments: ["%app_locales%"]
        tags:
            - { name: twig.extension }
  app.twig.my_app_extension:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }